name: Build NodeJS

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_call:
    inputs:
      cache-dependency-path:
        description: 'Where is your package.json file'
        type: string
        default: 'package-lock.json'
      node-js-version:
        description: 'Your Node.js version'
        type: string
        default: '18.x'

jobs:
  build-nodejs:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ inputs.node-js-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
          cache-dependency-path: ${{ inputs.cache-dependency-path }}
          node-version:       ${{ inputs.node-js-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
